- name: yum update
  yum:
    name: '*'
    state: latest

- name: vim install
  yum:
    name: vim-enhanced
    state: latest

- name: vim echo alias
  command: echo alias vi='vim' >> /etc/profile

- name: vim source change
  shell: source /etc/profile

- name: chrony install
  yum:
    name: chrony
    state: latest

- name: chrony enable
  systemd:
    name: chronyd
    enabled: yes

- name: chrony.conf replace
  replace:
    path: /etc/chrony.conf
    regexp: '^server 0.centos.pool.ntp.org iburst\nserver 1.centos.pool.ntp.org iburst\nserver 2.centos.pool.ntp.org iburst\nserver 3.centos.pool.ntp.org iburst$'
    replace: 'server ntp.nict.jp iburst\nserver ntp1.jst.mfeed.ad.jp iburst\nserver ntp2.jst.mfeed.ad.jp iburst\nserver ntp3.jst.mfeed.ad.jp iburst'
    backup: yes

- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: chrony reload
  systemd:
    name: chronyd
    state: started

- name: firewalld stop
  systemd:
    name: firewalld
    state: stopped

- name: firewalld disable
  systemd:
    name: firewalld
    enabled: no

- name: NKF download
  unarchive:
    src: http://sourceforge.jp/frs/redir.php?m=jaist&f=%2Fnkf%2F59912%2Fnkf-2.1.3.tar.gz
    dest: /tmp
    remote_src: yes

- name: NKF install
  make:
    chdir: /tmp/nkf-2.1.3

- name: NKF copy
  command: cp /tmp/nkf-2.1.3/nkf /usr/bin/

- name: NKF.tar.gz remove
  file:
    path: /tmp/nkf-2.1.3
    state: absent

- name: NKF.tar.gz remove
  file:
    path: /tmp/nkf-2.1.3
    state: absent

- name: LANG ja_JP.UTF-8 install
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - ibus-kkc
    - vlgothic-*

- name: LANG ja_JP.UTF-8 set
  command: localectl set-locale LANG=ja_JP.UTF-8