- name: repositry install
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - yum-plugin-priorities
  - epel-release

- name: repositry install
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: installed

- name: EPEL disabled
  replace:
    path: /etc/yum.repos.d/epel.repo
    regexp: '^enabled=1$'
    replace: 'enabled=0'
    backup: yes